export default [
  {
    "title": "Favorite Books",
    "isSeries": false,
    "items": [
      "The Crippled God",
      "Assassin's Quest",
      "The Republic of Thieves",
      "The Wisdom of Crowds",
      "Memories of Ice",
      "The Wise Man's Fear",
      "The Bonehunters",
      "Babel",
      "Demon in White",
      "Last Argument of Kings",
      "The Lies of Locke Lamora",
      "Best Served Cold",
      "The Will of the Many",
      "The Name of the Wind",
      "Words of Radiance",
      "Assassin's Apprentice",
      "The Thousand Deaths of Ardor Benn",
      "Empire of the Dawn",
      "The Hero of Ages",
      "Wintersteel",
      "The Blade Itself",
      "Hyperion",
      "The Mad Ship",
      "The Blackest Heart",
      "Deadhouse Gates",
      "Shadows Upon Time",
      "The Last Light",
      "Before They Are Hanged",
      "The Silence of the Lambs",
      "Blood Over Bright Haven",
      "The Way of Kings",
      "Sixteen Ways to Defend a Walled City",
      "Ender's Game",
      "Toll the Hounds",
      "A Wizard of Earthsea",
      "House of Chains",
      "Empire of the Damned",
      "Uncrowned",
      "Royal Assassin",
      "Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
      "A Little Hatred",
      "Gardens of the Moon",
      "The Trouble With Peace",
      "Red Seas Under Red Skies",
      "Reaper's Gale",
      "Disquiet Gods",
      "King of Duels",
      "The King of Attolia",
      "Of War and Ruin",
      "The Rains of Liscor",
      "The Horse and His Boy",
      "Howl's Moving Castle",
      "The Final Empire",
      "Mother of Learning: ARC 3",
      "Harry Potter and the Half-Blood Prince",
      "Ghostwater",
      "Harry Potter and the Deathly Hallows",
      "The Forgetting Moon",
      "Dust of Dreams",
      "Kings of the Wyld",
      "Hell's Wardens",
      "Daughter of the Empire",
      "Empire of the Vampire",
      "Return of the Thief",
      "The Hobbit",
      "Midnight Tides",
      "Dawn",
      "The Voyage of the Dawn Treader",
      "Tress of the Emerald Sea",
      "Guards! Guards!",
      "The Lion, The Witch and the Wardrobe",
      "Tears of Liscor",
      "Empire of Silence",
      "The Queen of Attolia",
      "Project Hail Mary",
      "The Heroes",
      "Exile",
      "The Palace Job",
      "The Rage of Dragons",
      "Blood Song",
      "The Lonesome Crown",
      "The Ruins of Gorlan",
      "Harry Potter and the Prisoner of Azkaban",
      "Reaper",
      "The Thief",
      "Mother of Learning: ARC 2",
      "The Four-Part Key",
      "Blood of Liscor",
      "The Sword of Kaigen",
      "Of Darkness and Light",
      "Children of Time",
      "Ready Player One",
      "Neverwhere",
      "Foundryside",
      "Legends & Lattes",
      "The Blacktongue Thief",
      "The Strength of the Few",
      "Empress of Beasts",
      "The Devils",
      "Eldest",
      "Erak's Ransom",
      "The Magician's Nephew",
      "Ship of Magic",
      "Inheritance",
      "The Tunnels Beneath",
      "1984",
      "Orconomics",
      "Piranesi"
    ]
  },
  {
    "title": "Favorite Series",
    "isSeries": true,
    "items": [
      "Malazan Book of the Fallen",
      "The Realm of the Elderlings",
      "First Law",
      "Gentleman Bastard",
      "The Kingkiller Chronicle",
      "The Sun Eater",
      "The Wandering Inn",
      "The Bound and the Broken",
      "Cosmere",
      "The Queen's Thief",
      "Cradle",
      "The Five Warrior Angels",
      "Empire of the Vampire",
      "Mother of Learning",
      "The Aldoran Chronicles",
      "Hierarchy",
      "The Siege",
      "The Chronicles of Narnia",
      "Earthsea Cycle",
      "Mark of the Fool",
      "The Expanse",
      "Ranger's Apprentice",
      "The Inheritance Cycle",
      "Dungeon Crawler Carl",
      "Harry Potter",
      "Shattered Sea",
      "The Legend of Drizzt",
      "The Maze Runner"
    ]
  },
  {
    "title": "Favorite Standalones",
    "isSeries": false,
    "items": [
      "Babel",
      "The Hobbit",
      "The Silence of the Lambs",
      "Blood Over Bright Haven",
      "The Sword of Kaigen",
      "Ender's Game",
      "Good Omens: The Nice and Accurate Prophecies of Agnes Nutter, Witch",
      "Project Hail Mary",
      "Howl's Moving Castle",
      "1984",
      "Between Two Fires"
    ]
  },
  {
    "title": "Favorite Trilogies",
    "isSeries": true,
    "items": [
      "The Farseer Trilogy",
      "The Age of Madness",
      "Gentleman Bastard",
      "The First Law",
      "The Five Warrior Angels",
      "Empire of the Vampire",
      "Mistborn",
      "The Siege",
      "Shattered Sea",
      "Kingdom of Grit",
      "The Legend of Drizzt"
    ]
  },
  {
    "title": "Best Lesser Known",
    "isSeries": true,
    "items": [
      "Kingdom of Grit",
      "The Bards and Dragons Saga",
      "The Wandering Inn",
      "Mistland",
      "The Aldoran Chronicles",
      "Rogues of the Republic",
      "Mother of Learning",
      "Mark of the Fool",
      "The Siege",
      "The Ripple System"
    ]
  },
  {
    "title": "Harry Potter Ranked",
    "isSeries": false,
    "items": [
      "Harry Potter and the Half-Blood Prince",
      "Harry Potter and the Deathly Hallows",
      "Harry Potter and the Prisoner of Azkaban",
      "Harry Potter and the Sorcerer's Stone",
      "Harry Potter and the Order of the Phoenix",
      "Harry Potter and the Goblet of Fire",
      "Harry Potter and the Chamber of Secrets"
    ]
  },
  {
    "title": "Narnia Ranked",
    "isSeries": false,
    "items": [
      "The Horse and His Boy",
      "The Voyage of the Dawn Treader",
      "The Lion, The Witch and the Wardrobe",
      "The Magician's Nephew",
      "The Last Battle",
      "Prince Caspian",
      "The Silver Chair"
    ]
  },
  {
    "title": "Malazan Ranked",
    "isSeries": false,
    "items": [
      "The Crippled God",
      "Memories of Ice",
      "The Bonehunters",
      "Deadhouse Gates",
      "Toll the Hounds",
      "House of Chains",
      "Gardens of the Moon",
      "Reaper's Gale",
      "Dust of Dreams",
      "Midnight Tides"
    ]
  },
  {
    "title": "Queen's Thief Ranked",
    "isSeries": false,
    "items": [
      "The King of Attolia",
      "Return of the Thief",
      "The Queen of Attolia",
      "The Thief",
      "Thick as Thieves",
      "A Conspiracy of Kings"
    ]
  },
  {
    "title": "Sun Eater Ranked",
    "isSeries": false,
    "items": [
      "Demon in White",
      "Shadows Upon Time",
      "Howling Dark",
      "Disquiet Gods",
      "Kingdoms of Death",
      "Empire of Silence",
      "Ashes of Man"
    ]
  },
  {
    "title": "The Wandering Inn Ranked",
    "isSeries": false,
    "items": [
      "The Last Light",
      "King of Duels",
      "Hell's Wardens",
      "The Rains of Liscor",
      "Tears of Liscor",
      "Fae and Fare",
      "The Wandering Inn",
      "The Titan of Baleros",
      "Empress of Beasts",
      "Blood of Liscor",
      "Garden of Sanctuary",
      "The Wandering Inn 18",
      "The General of Izril",
      "Flowers of Esthelm",
      "Winter Solstice",
      "Lady of Fire",
      "The Wind Runner",
      "The Witch of Webs"
    ]
  },
  {
    "title": "Cosmere Ranked",
    "isSeries": false,
    "items": [
      "Words of Radiance",
      "The Way of Kings",
      "The Hero of Ages",
      "The Lost Metal",
      "The Final Empire",
      "Arcanum Unbounded",
      "Shadows of Self",
      "Tress of the Emerald Sea",
      "Oathbringer",
      "The Emperor's Soul",
      "Rhythm of War",
      "The Bands of Mourning",
      "Elantris",
      "Warbreaker",
      "The Well of Ascension",
      "Wind and Truth",
      "The Alloy of Law",
      "Dawnshard",
      "The Sunlit Man",
      "Yumi and the Nightmare painter",
      "White Sand",
      "Edgedancer"
    ]
  },
  {
    "title": "Cosmere Reading Order",
    "isSeries": false,
    "items": [
      "The Final Empire",
      "The Well of Ascension",
      "The Hero of Ages",
      "The Way of Kings",
      "Words of Radiance",
      "Elantris",
      "The Emperor's Soul",
      "Warbreaker",
      "White Sand",
      "The Alloy of Law",
      "Shadows of Self",
      "The Bands of Mourning",
      "Arcanum Unbounded",
      "Oathbringer",
      "Dawnshard",
      "Rhythm of War",
      "The Lost Metal",
      "Tress of the Emerald Sea",
      "The Sunlit Man",
      "Yumi and the Nightmare painter",
      "Wind and Truth"
    ]
  },
  {
    "title": "Cradle Ranked",
    "isSeries": false,
    "items": [
      "Wintersteel",
      "Uncrowned",
      "Ghostwater",
      "Bloodline",
      "Reaper",
      "Underlord",
      "Blackflame",
      "Unsouled",
      "Skysworn",
      "Soulsmith",
      "Dreadgod",
      "Waybound"
    ]
  },
  {
    "title": "Favorite Video Games",
    "isSeries": false,
    "items": [
      "Talos Principle 1&2",
      "DOS2 & BG3",
      "Skyrim",
      "Minecraft & Terraria",
      "Destiny",
      "Outer Wilds",
      "Myst & Riven",
      "Slay the Spire 1 & 2",
      "Halo",
      "COD WaW & BO2 & MW3 & MW",
      "Lego Marvel Superheros",
      "Infinity Blade",
      "Little Big Planet",
      "Smash"
    ]
  }
];
