export default [
  {
    series: "Cradle",
    author: "Will Wight",
    title: "Soulsmith",
    question:
      "Which character has a name pronounced similarly to a national capital?",
    answer: "Yerin / Yaren (Nauru)",
    difficulty: "Hard",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Guards! Guards!",
    question: "What is the name of the large dwarf?",
    answer: "Carrot",
    difficulty: "Easy",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Guards! Guards!",
    question: "Who is the captain of the Night Watch?",
    answer: "Sam Vimes",
    difficulty: "Easy",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Mort",
    question: "Who takes Mort as an apprentice?",
    answer: "Death",
    difficulty: "Easy",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Mort",
    question: "What is the name of the great turtle?",
    answer: "A'Tuin",
    difficulty: "Easy",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Mort",
    question: "What is the name of Death's horse?",
    answer: "Binky",
    difficulty: "Medium",
  },
  {
    series: "Discworld",
    author: "Terry Pratchett",
    title: "Mort",
    question: "What is the rite used to summon and bind Death?",
    answer: "AshkEnte",
    difficulty: "Hard",
  },
  {
    series: "General",
    author: "N/A",
    title: "General",
    question: "What is the best selling novel in history?",
    answer: "Don Quixote",
    difficulty: "Easy",
  },
  {
    series: "Harry Potter",
    author: "J. K. Rowling",
    title: "Goblet of Fire",
    question:
      "Which character slept under a cloak propped up on sticks at the Quidditch World Cup Match",
    answer: "Mundungus Fletcher",
    difficulty: "Hard",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "Hyperion",
    question:
      "What were the original names of the 3 continents on the planet Hyperion?",
    answer: "Creighton, Allensen, and Lopez",
    difficulty: "Hard",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "Hyperion",
    question:
      "What is the name of the device that allows instant travel between worlds?",
    answer: "Farcaster",
    difficulty: "Easy",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "Hyperion",
    question: "Name of the tree-ship that takes the pilgrims to Hyperion?",
    answer: "Yggdrasil",
    difficulty: "Medium",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "Hyperion",
    question: "How many Bikura are there?",
    answer: "70 (Three score and ten)",
    difficulty: "Easy",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "Hyperion",
    question: "What is the name of Rachel's disease?",
    answer: "Merlin's Sickness",
    difficulty: "Hard",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "The Fall of Hyperion",
    question:
      "What is the name of John Keats' friend, the artist who was with him when he died?",
    answer: "Joseph Severn",
    difficulty: "Easy",
  },
  {
    series: "Hyperion Cantos",
    author: "Dan Simmons",
    title: "The Fall of Hyperion",
    question: "Where is the Technocore located?",
    answer: "In the Farcasters",
    difficulty: "Easy",
  },
  {
    series: "Liveship Traders",
    author: "Robin Hobb",
    title: "Mad Ship",
    question: "What do you call the women who live with and advise the Satrap?",
    answer: "Companions of the Heart",
    difficulty: "Medium",
  },
  {
    series: "Liveship Traders",
    author: "Robin Hobb",
    title: "Ship of Magic",
    question:
      "What words do the serpents use to refer to the space above the sea and in the water?",
    answer: "Lack and Plenty",
    difficulty: "Medium",
  },
  {
    series: "Liveship Traders",
    author: "Robin Hobb",
    title: "Mad Ship",
    question: "Name of the city where Reyn lives on the Rain Wild river?",
    answer: "Trehaug",
    difficulty: "Easy",
  },
  {
    series: "Liveship Traders",
    author: "Robin Hobb",
    title: "Mad Ship",
    question: "Name of the dragon freed at the end of the book?",
    answer: "Tintaglia",
    difficulty: "Medium",
  },
  {
    series: "Liveship Traders",
    author: "Robin Hobb",
    title: "Mad Ship",
    question: "What is a formal term of address / honorific for the Satrap?",
    answer: "Magnadon",
    difficulty: "Medium",
  },
  {
    series: "Lord of the Rings",
    author: "J. R. R. Tolkien",
    title: "Movies",
    question:
      "Which cast member of the movies was the only one to meet Tolkien?",
    answer: "Christopher Lee",
    difficulty: "Easy",
  },
  {
    series: "Malazan",
    author: "Steven Erikson, Ian C. Esslemont",
    title: "General",
    question:
      "If you were to read the books in the Malazan universe in chronological order, which book should you read first?",
    answer: "Forge of Darkness",
    difficulty: "Medium",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What is the Sithi name for Hayholt?",
    answer: "Asu'a",
    difficulty: "Easy",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What is the name of King Prester John's sword?",
    answer: "Bright-Nail",
    difficulty: "Easy",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What is the name of the dragon killed by King Prester John?",
    answer: "Shurakai",
    difficulty: "Medium",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What is the name of the god of Prester John's kingdom?",
    answer: "Usires Aedon",
    difficulty: "Easy",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What was the Sithi name of the Storm King?",
    answer: "Ineluki",
    difficulty: "Medium",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "How many members are in the League of the Scroll?",
    answer: "7",
    difficulty: "Medium",
  },
  {
    series: "Memory, Sorrow, and Thorn",
    author: "Tad Williams",
    title: "The Dragonbone Chair",
    question: "What is the name of the ruined Sithi city Simon passes through?",
    answer: "Da'ai Chikiza",
    difficulty: "Hard",
  },
  {
    series: "Mistborn",
    author: "Brandon Sanderson",
    title: "The Well of Ascension",
    question: "Who is the main characters boyfriends half-brothers father?",
    answer: "Lord Straff",
    difficulty: "Medium",
  },
  {
    series: "Mistborn",
    author: "Brandon Sanderson",
    title: "The Final Empire",
    question: "What are the two metals used for Pushing and Pulling?",
    answer: "Iron and Steel",
    difficulty: "Easy",
  },
  {
    series: "N/A",
    author: "Jane Austen",
    title: "Pride and Prejudice",
    question: "Who does Jane Bennet marry? ",
    answer: "Charles Bingley",
    difficulty: "Medium",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "How many miles across is the Metaverse?",
    answer: "2^16 (65,536)",
    difficulty: "Hard",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "What is the derogative term for a minivan?",
    answer: "Bimbo Box",
    difficulty: "Easy",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "What college did Hiro go to with Juanita?",
    answer: "Berkeley",
    difficulty: "Hard",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "Which character shares a name with a former national capital?",
    answer: "Lagos (Nigeria)",
    difficulty: "Medium",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "What do the initials Y.T. stand for?",
    answer: "Yours Truly",
    difficulty: "Hard",
  },
  {
    series: "N/A",
    author: "Neal Stephenson",
    title: "Snow Crash",
    question: "What is Hiro's job at the start of the book?",
    answer: "Deliverator",
    difficulty: "Easy",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question:
      "What is the proper term to use as a Common when Addressing a Noble?",
    answer: "Nkosi",
    difficulty: "Medium",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question: "What is the name of Tau's Father?",
    answer: "Aren",
    difficulty: "Easy",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question: "What is the name of the ship Queen Taifa arrives on?",
    answer: "Targon",
    difficulty: "Hard",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question: "What Scale is Tau a member of?",
    answer: "Scale Jayyed",
    difficulty: "Easy",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question: "What are the names of the three most common types of magic?",
    answer: "Enervate, Enrage, Entreat",
    difficulty: "Easy",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question:
      "What is the name of the realm of Ukufa? (The place you draw power from to perform magic, and the land where demons roam)",
    answer: "Isihogo",
    difficulty: "Medium",
  },
  {
    series: "The Burning",
    author: "Evan Winter",
    title: "The Rage of Dragons",
    question: "List all of the Chosen Castes from top to bottom",
    answer:
      "Queen (& Royal Family), Royal Nobles, GIfted, Ingonyama, Greater Nobles, Petty Nobles, Ihashe, High Governor, Low Governor, High Harvester, Low Harvester, High Common, Low Common, Drudge",
    difficulty: "Hard",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Leviathan Wakes",
    question:
      "What is the name of the ice hauler Jim works on at the start of the series?",
    answer: "The Canterbury",
    difficulty: "Medium",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Leviathan Wakes",
    question:
      "What does Jim rename the martian ship he and his crew use to flee to Tycho Station?",
    answer: "The Rocinante",
    difficulty: "Easy",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Cibola Burn",
    question:
      "What name does the UN try to give to the central planet of the novel?",
    answer: "New Terra",
    difficulty: "Medium",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Leviathan Wakes",
    question: "What moon was the protomolecule discovered in?",
    answer: "Phoebe",
    difficulty: "Easy",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Leviathan Wakes",
    question: "What is Detective Miller's first name?",
    answer: "Josephus",
    difficulty: "Medium",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Nemesis Games",
    question: "What is the name of Alex's ex wife?",
    answer: "Talissa",
    difficulty: "Hard",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Leviathan Wakes",
    question: "What is the name of the company owned by Jules-Pierre Mao?",
    answer: "Mao-Kwikowski Mercantile",
    difficulty: "Medium",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Nemesis Games",
    question: "What is the name of Naomi's son?",
    answer: "Filip",
    difficulty: "Easy",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Persepolis Rising",
    question: "What is the name of the new empire formed by Winston Duarte?",
    answer: "Laconia",
    difficulty: "Easy",
  },
  {
    series: "The Expanse",
    author: "James S. A. Corey",
    title: "Tiamat's Wrath",
    question:
      "What is the name of the system Elvi finds that contains only a neutron star?",
    answer: "Tecoma System",
    difficulty: "Hard",
  },
];
