export default [
{ word:	"Abattoir",	definition: 	"A slaughterhouse"	},
{ word:	"Acrimonious",	definition: 	"Angry and Bitter"	},
{ word:	"Aegis",	definition: 	"Protection, Shield in Greek myth"	},
{ word:	"Agglutinative",	definition: 	"A word formed by shoving other words together"	},
{ word:	"Aggrandizement",	definition: 	"Increasing the power of something"	},
{ word:	"Anaphylaxis",	definition: 	"Severe, potentially life-threatening allergic reaction"	},
{ word:	"Antecedent",	definition: 	"Preceding in time or order"	},
{ word:	"Apoplexy",	definition: 	"Unconsciousness or incapacity resulting from a cerebral hemorrhage or stroke"	},
{ word:	"Appellation",	definition: 	"Name or title"	},
{ word:	"Apsis",	definition: 	"The point in an astronomical orbit at which the distance of the body from the center of attraction is either greatest or least"	},
{ word:	"Arbitrary",	definition: 	"Based on random choice or personal whim, rather than any reason or system"	},
{ word:	"Arcology",	definition: 	"A city intended to be contained in a single structure"	},
{ word:	"Argot",	definition: 	"The jargon or slang of a particular group or class"	},
{ word:	"Arrears",	definition: 	"Money that is owed and should have been paid earlier"	},
{ word:	"Asinine",	definition: 	"Extremely stupid or foolish"	},
{ word:	"Assay",	definition: 	"The testing of a metal or ore to determine its ingredients and quality"	},
{ word:	"Astringent",	definition: 	"Slightly acidic or bitter"	},
{ word:	"Atavistic",	definition: 	"Relating to or characterized by reversion to something ancient or ancestral"	},
{ word:	"Autoclave",	definition: 	"A machine used to carry out industrial and scientific processes requiring elevated temperature and pressure"	},
{ word:	"Avuncular",	definition: 	"Relating to an uncle"	},
{ word:	"Banjax",	definition: 	"Ruin, incapacitate, or break"	},
{ word:	"Barrister",	definition: 	"A lawyer entitled to practice as an advocate, particularly in the higher courts"	},
{ word:	"Beige",	definition: 	"Lacking distinction"	},
{ word:	"Bellicose",	definition: 	"Demonstrating aggression and willingness to fight"	},
{ word:	"Bespawl",	definition: 	"To spatter with or as if with saliva"	},
{ word:	"Bier",	definition: 	"A movable frame on which a coffin or a corpse is placed before burial or cremation or on which it is carried to the grave"	},
{ word:	"Bilious",	definition: 	"Affected by or associated with nausea or vomiting"	},
{ word:	"Bollard",	definition: 	"A short, sturdy vertical post used to control traffic, enhance security, or moor vessels"	},
{ word:	"Bonce",	definition: 	"A person's head"	},
{ word:	"Bordello",	definition: 	"A brothel"	},
{ word:	"Bort",	definition: 	"An umbrella term used in the diamond industry to refer to shards of non-gem-grade/quality diamonds"	},
{ word:	"Busker",	definition: 	"A person who performs music or other entertainment in the street or another public place for monetary donations"	},
{ word:	"Callow",	definition: 	"Inexperienced and immature"	},
{ word:	"Caprice",	definition: 	"A sudden and unaccountable change of mood or behavior"	},
{ word:	"Cassoulet",	definition: 	"A rich stew originating in southern France"	},
{ word:	"Castrati",	definition: 	"Castrati were male singers castrated before puberty to preserve high soprano or alto vocal ranges"	},
{ word:	"Catamite",	definition: 	"A boy kept for homosexual practices"	},
{ word:	"Caudal",	definition: 	"Of or like a tail"	},
{ word:	"Cerise",	definition: 	"A bright or deep red color"	},
{ word:	"Chantry",	definition: 	"An endowment for a priest or priests to celebrate masses for the founder's soul"	},
{ word:	"Chapeau",	definition: 	"A hat or cap"	},
{ word:	"Chiral",	definition: 	"Molecules or objects that cannot be superimposed on their mirror images"	},
{ word:	"Chivvied",	definition: 	"Tell (someone) repeatedly to do something"	},
{ word:	"Churl",	definition: 	"An impolite and mean-spirited person"	},
{ word:	"Clavier",	definition: 	"A keyboard instrument, especially one with strings, such as the harpsichord"	},
{ word:	"Cloche",	definition: 	"A bell or dome shaped cover"	},
{ word:	"Cockle",	definition: 	"A small, shallow boat"	},
{ word:	"Cogent",	definition: 	"Clear, logical, and convincing"	},
{ word:	"Cogitate",	definition: 	"Think deeply about something; meditate or reflect"	},
{ word:	"Collegial",	definition: 	"Relating to or involving shared responsibility, as among a group of colleagues"	},
{ word:	"Conniption",	definition: 	"A fit of rage or hysterics"	},
{ word:	"Contrail",	definition: 	"Streaks of condensed water vapor created in the air by an airplane or rocket at high altitudes"	},
{ word:	"Contrition",	definition: 	"The state of feeling remorseful and penitent"	},
{ word:	"Convivial",	definition: 	"Friendly, lively, and enjoyable"	},
{ word:	"Coquettish",	definition: 	"Flirtatious"	},
{ word:	"Cordite",	definition: 	"A smokeless explosive"	},
{ word:	"Cosset",	definition: 	"Care for and protect in an overindulgent way"	},
{ word:	"Coxcomb",	definition: 	"A vain and conceited man"	},
{ word:	"Dearth",	definition: 	"A scarcity or lack of something"	},
{ word:	"Decolletage",	definition: 	"A low neckline on a woman's dress or top"	},
{ word:	"Defilade",	definition: 	"The protection of a position, vehicle, or troops against enemy observation or gunfire"	},
{ word:	"Deleterious",	definition: 	"Causing harm or damage"	},
{ word:	"Demitasse",	definition: 	"Espresso cup"	},
{ word:	"Demur",	definition: 	"Raise doubts or objections or show reluctance"	},
{ word:	"Diaspora",	definition: 	"The dispersion or spread of a people from their original homeland"	},
{ word:	"Dray",	definition: 	"A truck or cart for delivering beer barrels or other heavy loads, especially a low one without sides"	},
{ word:	"Drivel",	definition: 	"Nonsense"	},
{ word:	"Dudgeon",	definition: 	"A feeling of offense or deep resentment"	},
{ word:	"Ecdysiast",	definition: 	"A striptease performer"	},
{ word:	"Ecumenical",	definition: 	"Representing a number of different Christian Churches"	},
{ word:	"Effluvium",	definition: 	"An unpleasant or harmful odor, secretion, or discharge"	},
{ word:	"Endemic",	definition: 	"Native and restricted to a certain place"	},
{ word:	"Enervate",	definition: 	"Cause (someone) to feel drained of energy or vitality; weaken"	},
{ word:	"Ennui",	definition: 	"A feeling of listlessness and dissatisfaction arising from a lack of occupation or excitement"	},
{ word:	"Epaulet",	definition: 	"An ornamental shoulder piece or decoration used on uniforms to signify rank"	},
{ word:	"Epicanthic",	definition: 	"Denoting a fold of skin from the upper eyelid covering the inner angle of the eye"	},
{ word:	"Epicurean",	definition: 	"A person devoted to refined sensuous enjoyment, particularly luxurious food and drink"	},
{ word:	"Epigram",	definition: 	"A pithy saying or remark expressing an idea in a clever and amusing way"	},
{ word:	"Equippage",	definition: 	"The equipment, outfit, or necessary items for a specific purpose, particularly in military or travel contexts"	},
{ word:	"Eschatology",	definition: 	"The part of theology concerned with death, judgment, and the final destiny of the soul and of humankind"	},
{ word:	"Excrescence",	definition: 	"A distinct outgrowth on a human or animal body or on a plant, especially one that is the result of disease or abnormality"	},
{ word:	"Expiate",	definition: 	"Atone for (guilt or sin)"	},
{ word:	"Exsanguinate",	definition: 	"Drain a person or animal of blood, or to make them bloodless; MTG card"	},
{ word:	"Extemporaneous",	definition: 	"Spoken or done without preparation"	},
{ word:	"Faff",	definition: 	"Spend time on unnecessarily complicated and time-consuming actions"	},
{ word:	"Fane",	definition: 	"A temple or shrine; DOS2 Character"	},
{ word:	"Felicitation",	definition: 	"Words expressing praise for an achievement or good wishes on a special occasion"	},
{ word:	"Felonious",	definition: 	"Relating to or involved in crime"	},
{ word:	"Fettle",	definition: 	"State or condition of health"	},
{ word:	"Fiducial",	definition: 	"Assumed as a fixed basis of comparison"	},
{ word:	"Firmament",	definition: 	"A celestial barrier that separated the Heavenly waters above from the Earth below"	},
{ word:	"Foment",	definition: 	"Instigate or stir up"	},
{ word:	"Fulminate",	definition: 	"Express vehement protest"	},
{ word:	"Fulsome",	definition: 	"Complimentary or flattering to an excessive degree"	},
{ word:	"Funicular",	definition: 	"A type of cable railway system that connects points along a railway track laid on a steep slope"	},
{ word:	"Gantry",	definition: 	"An overhead bridge-like structure supporting equipment"	},
{ word:	"Garrulous",	definition: 	"Excessively talkative, especially on trivial matters"	},
{ word:	"Gauche",	definition: 	"Lacking ease or grace; unsophisticated and socially awkward"	},
{ word:	"Gendarmeria",	definition: 	"A military force with law enforcement duties among the civilian population, often serving as border guards or rural police"	},
{ word:	"Genteel",	definition: 	"Polite, refined, or respectable, often in an affected or ostentatious way"	},
{ word:	"Genuflect",	definition: 	"Lower one's body briefly by bending one knee to the ground, typically in worship or as a sign of respect"	},
{ word:	"Geocarpy",	definition: 	"An extremely rare means of plant reproduction, in which plants produce diaspores within the soil"	},
{ word:	"Gibbet",	definition: 	"Gallows"	},
{ word:	"Goji",	definition: 	"Red Berry"	},
{ word:	"Gongfarmer",	definition: 	"Someone who dug out and removed human excrement from privies and cesspits"	},
{ word:	"Gorget",	definition: 	"A piece of armor designed to protect the throat and neck"	},
{ word:	"Gormless",	definition: 	"Lacking sense or initiative; foolish"	},
{ word:	"Grafter",	definition: 	"Someone who obtains money dishonestly through corruption; British: Hard worker"	},
{ word:	"Grist",	definition: 	"Grain that is ground to make flour; MTG Planeswalker"	},
{ word:	"Halidom",	definition: 	"Something held sacred"	},
{ word:	"Harangue",	definition: 	"A lengthy and aggressive speech"	},
{ word:	"Hauberk",	definition: 	"A knee-length, long-sleeved chainmail shirt designed to protect a warrior’s torso and thighs"	},
{ word:	"Hellion",	definition: 	"A rowdy, mischievous, or troublemaking person, especially a child"	},
{ word:	"Histrionic",	definition: 	"Overly theatrical or melodramatic in character or style"	},
{ word:	"Huckster",	definition: 	"A person who sells small items, either door-to-door or from a stall or small store"	},
{ word:	"Idempotency",	definition: 	"Denoting an element of a set which is unchanged in value when multiplied or otherwise operated on by itself"	},
{ word:	"Ignominious",	definition: 	"Deserving or causing public disgrace or shame"	},
{ word:	"Impavid",	definition: 	"Fearless"	},
{ word:	"Ingenue",	definition: 	"An innocent or unsophisticated young woman, especially in a play or film"	},
{ word:	"Ingress",	definition: 	"The action or fact of going in or entering; Phone game"	}
];